### ISSUE TITLE
Integrating this with Ionic2

### ISSUE THREAD

**Issue by gbrigens** [neshoj/safaricom-daraja-nodejs#1]
@neshoj Thanks for drama project. Quick one looking on ways of using this on my ionic 3 app which utilizes firebase as a server. Is here a way of utilizing this api directly like PayPal or stripe without having to use nodejs?

I will appreciate your feedback.

Gerald.

**Comment by neshoj** [comment]
I initially built the API as a standalone solution that you can deploy directly on your server, configure your custom pay bill short code and credentials then start processing requests. You have made reference to having the same service offered as a payment gateway, this is not available but I am working on something that will be able to that in the future.

**Comment by gbrigens** [comment]
Thanks for your feedback.
