### ISSUE TITLE
There is no npm start as described in the documentation

### ISSUE THREAD

**Issue by Oneted11** [neshoj/safaricom-daraja-nodejs#3]

**Comment by mosseti** [comment]
same problem, here's the log

0 info it worked if it ends with ok
1 verbose cli [ '/home/brian/.nvm/versions/node/v11.7.0/bin/node',
1 verbose cli   '/home/brian/.nvm/versions/node/v11.7.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.5.0
3 info using node@v11.7.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/home/brian/.nvm/versions/node/v11.7.0/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /home/brian/.nvm/versions/node/v11.7.0/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /home/brian/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /home/brian/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/home/brian/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/home/brian/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/home/brian/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /home/brian/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
4 verbose stack     at /home/brian/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
5 verbose cwd /media/brian/local disk d1/viatu/saf/saf2/safaricom-daraja-nodejs
6 verbose Linux 4.13.0-45-generic
7 verbose argv "/home/brian/.nvm/versions/node/v11.7.0/bin/node" "/home/brian/.nvm/versions/node/v11.7.0/bin/npm" "start"
8 verbose node v11.7.0
9 verbose npm  v6.5.0
10 error missing script: start
11 verbose exit [ 1, true ]

**Comment by neshoj** [comment]
This has been resolved
