### ISSUE TITLE
STK PUSH

### ISSUE THREAD

**Issue by charliekaks** [neshoj/safaricom-daraja-nodejs#5]
Hey, am loving your node app really convenient. One issue though when I send the stk push I get `{
    "status": "01",
    "message": "Invalid remote response"
}`
but the stk still shows up and confirms my payment. What could be the issue?

**Comment by charliekaks** [comment]
I was doing some debugging after getting the above response and I made a change in the `mpesaFunctions.js` file. I think one of the conditions in httpResponseBodyProcessor function should not have a `!` the `isEmpty(responseData.body.status)`. After the change, it worked. Am not sure of the solution please review and confirm

**Comment by neshoj** [comment]
Hi @charliekaks allow me review the above issue and provide feedback on it

**Comment by neshoj** [comment]
Hi @charliekaks allow me review the above issue and provide feedback on it

**Comment by neshoj** [comment]
Hi @charliekaks after very many months I have returned to resolve the issue, check the latest update. I wouldn't mind having you as a contributor to the project by the way.
